name: Blog
on: [push]

jobs:
  build:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install npm
      run: npm install 
    - name: Build 
      run: npm run-script build



